### ISSUE TITLE
大佬可以获取apple watch或airtag的IRK吗

### ISSUE THREAD

**Issue by gmshiwoge** [fryefryefrye/Decoding-Random-Bluetooth-Address#2]
可以获取apple watch或airtag的IRK吗

**Comment by fryefryefrye** [comment]
不会。我都买不起这些设备，哈哈哈哈。





------------------ 原始邮件 ------------------
发件人: gmshiwoge ***@***.***&gt;
发送时间: 2022年6月30日 14:46
收件人: fryefryefrye/Decoding-Random-Bluetooth-Address ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [fryefryefrye/Decoding-Random-Bluetooth-Address] 大佬可以获取apple watch或airtag的IRK吗 (Issue #2)

**Comment by gmshiwoge** [comment]
哈哈哈这样 airtag好像都便宜下来了 谢谢了

**Comment by fryefryefrye** [comment]
手表的话，你看看能不能开发一个，或者找一个苹果手表应用，来链接ESP 32开出来的蓝牙服务。


airtag 的话，我还想不出什么方案呢。





------------------ 原始邮件 ------------------
发件人: gmshiwoge ***@***.***&gt;
发送时间: 2022年6月30日 14:46
收件人: fryefryefrye/Decoding-Random-Bluetooth-Address ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [fryefryefrye/Decoding-Random-Bluetooth-Address] 大佬可以获取apple watch或airtag的IRK吗 (Issue #2)





 
可以获取apple watch或airtag的IRK吗

**Comment by fryefryefrye** [comment]
> 哈哈哈这样 airtag好像都便宜下来了 谢谢了

看看下面的介绍，用来获得苹果手表的IRK。不知道能不能搞到airtag。
https://espresense.com/beacons/apple

**Comment by fryefryefrye** [comment]
> 可以获取apple watch或airtag的IRK吗

https://espresense.com/beacons
里面写了，Apple AirTags 不可用。

**Comment by fryefryefrye** [comment]
https://community.home-assistant.io/t/guide-getting-the-irk-for-iphone-and-apple-watch-without-macos-maybe-also-other-devices/623694/12

根据上面这个帖子，苹果手表也可以用我提供的方法获得IRK。
