### ISSUE TITLE
Running on ESP32S3

### ISSUE THREAD

**Issue by gedger** [fryefryefrye/Decoding-Random-Bluetooth-Address#4]
I'm trying to get this running on a (LOLIN S3 Mini), compiles fine but gives no output. Is this only compatible with the standard ESP32Dev board?

**Comment by fryefryefrye** [comment]
I think S3 do not have UART output via USB port. 
You need a USB-Uart converter to connect the UART_0 pins of the S3.

**Comment by gedger** [comment]
Thank you, connecting to UART0 shows.

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a68
entry 0x403c98d4
[   180][E][esp32_irk.h:842] BT_Init(): [SEC_GATTS_DEMO] GATTS Starting...
[   232][V][esp32_irk.h:695] gatts_profile_event_handler(): [SEC_GATTS_DEMO] event = 0  ESP_GATTS_REG_EVT
[   234][V][esp32_irk.h:695] gatts_profile_event_handler(): [SEC_GATTS_DEMO] event = 22  ESP_GATTS_CREAT_ATTR_TAB_EVT
[   241][I][esp32_irk.h:747] gatts_profile_event_handler(): [SEC_GATTS_DEMO] The number handle = 8
[   249][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:22 ESP_GAP_BLE_SET_LOCAL_PRIVACY_COMPLETE_EVT
[   262][V][esp32_irk.h:695] gatts_profile_event_handler(): [SEC_GATTS_DEMO] event = 12  ESP_GATTS_START_EVT
[   270][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:0 ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT
[   281][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:1 ESP_GAP_BLE_SCAN_RSP_DATA_SET_COMPLETE_EVT
E (413) BT_BTM: No random address yet, please set random address and try

E (420) BT_APPL: bta_dm_ble_set_adv_params_all(), fail to set ble adv params.
[   306][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:6 ESP_GAP_BLE_ADV_START_COMPLETE_EVT
[   316][E][esp32_irk.h:600] gap_event_handler(): [SEC_GATTS_DEMO] advertising start failed, error status = 1
[   325][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:6 ESP_GAP_BLE_ADV_START_COMPLETE_EVT
[   336][E][esp32_irk.h:600] gap_event_handler(): [SEC_GATTS_DEMO] advertising start failed, error status = d
```

**Comment by fryefryefrye** [comment]
> Thank you, connecting to UART0 shows.
> 
> ```
> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
> SPIWP:0xee
> mode:DIO, clock div:1
> load:0x3fce3808,len:0x44c
> load:0x403c9700,len:0xbe4
> load:0x403cc700,len:0x2a68
> entry 0x403c98d4
> [   180][E][esp32_irk.h:842] BT_Init(): [SEC_GATTS_DEMO] GATTS Starting...
> [   232][V][esp32_irk.h:695] gatts_profile_event_handler(): [SEC_GATTS_DEMO] event = 0  ESP_GATTS_REG_EVT
> [   234][V][esp32_irk.h:695] gatts_profile_event_handler(): [SEC_GATTS_DEMO] event = 22  ESP_GATTS_CREAT_ATTR_TAB_EVT
> [   241][I][esp32_irk.h:747] gatts_profile_event_handler(): [SEC_GATTS_DEMO] The number handle = 8
> [   249][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:22 ESP_GAP_BLE_SET_LOCAL_PRIVACY_COMPLETE_EVT
> [   262][V][esp32_irk.h:695] gatts_profile_event_handler(): [SEC_GATTS_DEMO] event = 12  ESP_GATTS_START_EVT
> [   270][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:0 ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT
> [   281][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:1 ESP_GAP_BLE_SCAN_RSP_DATA_SET_COMPLETE_EVT
> E (413) BT_BTM: No random address yet, please set random address and try
> 
> E (420) BT_APPL: bta_dm_ble_set_adv_params_all(), fail to set ble adv params.
> [   306][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:6 ESP_GAP_BLE_ADV_START_COMPLETE_EVT
> [   316][E][esp32_irk.h:600] gap_event_handler(): [SEC_GATTS_DEMO] advertising start failed, error status = 1
> [   325][V][esp32_irk.h:580] gap_event_handler(): [SEC_GATTS_DEMO] GAP_EVT, event:6 ESP_GAP_BLE_ADV_START_COMPLETE_EVT
> [   336][E][esp32_irk.h:600] gap_event_handler(): [SEC_GATTS_DEMO] advertising start failed, error status = d
> ```

I create this project years ago, and I'm just start to play with ESP32S3.
So, got a standard ESP32Dev board is a easy way to get the IRK.

**Comment by gedger** [comment]
No problems, I don't have a standard ESP32 available at the moment so thought I'd try the S3. I'll do a bit of debugging myself until I get one.
Thanks again.

**Comment by FlyGoat** [comment]
I was messing around this project on ESP32-C3 and came up with #5 as solution.

**Comment by gedger** [comment]
Confirmed patch working on  ESP32-S3. Thank you.
